// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABSrOn-usJQOJLaR2djLz77zf34ZHDZAk',
    appId: '1:828477604886:web:53ef690efc5ed49e452137',
    messagingSenderId: '828477604886',
    projectId: 'my-shopping-app-50859',
    authDomain: 'my-shopping-app-50859.firebaseapp.com',
    storageBucket: 'my-shopping-app-50859.firebasestorage.app',
    measurementId: 'G-D1FQGYZR9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgSQSt3DFrUW5agcPn699liOMT4Q5qxEQ',
    appId: '1:828477604886:android:fd542bb517688520452137',
    messagingSenderId: '828477604886',
    projectId: 'my-shopping-app-50859',
    storageBucket: 'my-shopping-app-50859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6YONl3GYV9D4WdGPMSijCVHrBfvxOPQA',
    appId: '1:828477604886:ios:f8a967bdbceff8b9452137',
    messagingSenderId: '828477604886',
    projectId: 'my-shopping-app-50859',
    storageBucket: 'my-shopping-app-50859.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6YONl3GYV9D4WdGPMSijCVHrBfvxOPQA',
    appId: '1:828477604886:ios:f8a967bdbceff8b9452137',
    messagingSenderId: '828477604886',
    projectId: 'my-shopping-app-50859',
    storageBucket: 'my-shopping-app-50859.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABSrOn-usJQOJLaR2djLz77zf34ZHDZAk',
    appId: '1:828477604886:web:3afff87679c86d36452137',
    messagingSenderId: '828477604886',
    projectId: 'my-shopping-app-50859',
    authDomain: 'my-shopping-app-50859.firebaseapp.com',
    storageBucket: 'my-shopping-app-50859.firebasestorage.app',
    measurementId: 'G-4CX3KF5VKF',
  );

}